version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jsonforms-vue-seed
    volumes:
      - ../..:/workspaces:cached
      - ${ROOTCA}:/home/node/.local/share/mkcert:cached
    command: sleep infinity
    extra_hosts:
      - "host.docker.internal:host-gateway"
